// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWRO5ajk5vb2m8djtq7r722g_yGf7IIU',
    appId: '1:989925385010:web:214028af269a052d242d2b',
    messagingSenderId: '989925385010',
    projectId: 'diary-app-42-9ebfb',
    authDomain: 'diary-app-42-9ebfb.firebaseapp.com',
    storageBucket: 'diary-app-42-9ebfb.firebasestorage.app',
    measurementId: 'G-PZEYS046L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07_1exFKIaShtOgDke6tr1sYhGs5CHQ0',
    appId: '1:989925385010:android:fc0b5c1d4e197fa3242d2b',
    messagingSenderId: '989925385010',
    projectId: 'diary-app-42-9ebfb',
    storageBucket: 'diary-app-42-9ebfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxz4kkFLR87aO1VDj3XfmSAk45mR5LvLw',
    appId: '1:989925385010:ios:e45e67aaa5cf62cc242d2b',
    messagingSenderId: '989925385010',
    projectId: 'diary-app-42-9ebfb',
    storageBucket: 'diary-app-42-9ebfb.firebasestorage.app',
    iosClientId: '989925385010-oqm8n4cgnj8brubf1ubmv41v9omf453o.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxz4kkFLR87aO1VDj3XfmSAk45mR5LvLw',
    appId: '1:989925385010:ios:e45e67aaa5cf62cc242d2b',
    messagingSenderId: '989925385010',
    projectId: 'diary-app-42-9ebfb',
    storageBucket: 'diary-app-42-9ebfb.firebasestorage.app',
    iosClientId: '989925385010-oqm8n4cgnj8brubf1ubmv41v9omf453o.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGWRO5ajk5vb2m8djtq7r722g_yGf7IIU',
    appId: '1:989925385010:web:8f1c382c37f97db6242d2b',
    messagingSenderId: '989925385010',
    projectId: 'diary-app-42-9ebfb',
    authDomain: 'diary-app-42-9ebfb.firebaseapp.com',
    storageBucket: 'diary-app-42-9ebfb.firebasestorage.app',
    measurementId: 'G-NLDLKTPPLP',
  );

}